### ISSUE TITLE
Dependencies load order overwriting dplyr

### ISSUE THREAD

**Issue by Tess-LaCoil** [traitecoevo/hmde#35]
```
Warning messages:
1: replacing previous import ‘dplyr::lag’ by ‘stats::lag’ when loading ‘hmde’ 
2: replacing previous import ‘dplyr::filter’ by ‘stats::filter’ when loading ‘hmde’
```
Warning message appears when load_all() is used.

**Comment by Tess-LaCoil** [comment]
```
W  checking whether package 'hmde' can be installed (5m 58.8s)
   Found the following significant warnings:
     Warning: replacing previous import 'dplyr::lag' by 'stats::lag' when loading 'hmde'
     Warning: replacing previous import 'dplyr::filter' by 'stats::filter' when loading 'hmde'
```
Also occurs in rcmdcheck()

**Comment by dfalster** [comment]
I'm not seeing these at my end. Nor are they appearing in the tests on github. the only that comes up are some "NOTES", that are being address via #38 

See https://github.com/traitecoevo/hmde/actions/runs/10280200189/job/28447022963#step:6:47

so I suspect these messages are appearing because of a way you've loaded packages in your local setup. I commonly see similar messages happen when I load dplyr, e.g.

```
> library(dplyr)

Attaching package: ‘dplyr’

The following object is masked from ‘package:testthat’:

    matches

The following objects are masked from ‘package:stats’:

    filter, lag
```

You have the reverse. So perhaps you already had dplyr loaded, then reloaded stats? 

I dunno sorry. 

Try cloning from GitHub into a new directory and opening a new R session then running checks. Does it happen then? If not, it's something to do with contents of your local copy.
